name: Build executable
on:
 - push
 - workflow_dispatch
 - pull_request
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun i
      - name: Build
        run: bun build ./index.js --compile --outfile inject0r
      - name: Bundle
        run: |
          mkdir dist
          cp inject0r dist
          cp -r server dist
          cp -r public dist
        shell: bash
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: dist
